<?php
/**
 * Created by PhpStorm.
 * User: umberto
 * Date: 21/08/2018
 * Time: 16:42
 */

namespace UdeslyCustomizer\Plugins\Woocommerce;

class Woocommerce_Init_Settings{
	public static $settings = array (
		'woocommerce' =>
			array (
				'woo_btn_font_size' => 1,
				'woo_btn_font_color' => '#ffffff',
				'woo_btn_font_color_hover' => '#ffffff',
				'woo_btn_background_color' => '#a46497',
				'woo_btn_background_color_hover' => '#935386',
				'woo_btn_border_size' => 0,
				'woo_btn_border_color' => '#ffffff',
				'woo_btn_border_radius' => 3,
				'woo_table_padding' => 0.6,
				'woo_table_border_color' => '#D3CED2',
				'woo_header_background_color' => '#ffffff',
				'woo_product_background_color' => '#ffffff',
				'woo_product_table_border_size' => 1,
				'woo_product_table_border_color' => '#333333',
				'woo_product_table_corners' => 5,
				'woo_products_table_labels_font_size' => 14,
				'woo_products_table_labels_font_color' => '#333333',
				'woo_products_table_texts_font_size' => 14,
				'woo_products_table_texts_font_color' => '#333333',
				'woo_form_input_background_color' => '#ffffff',
				'woo_form_input_color' => '#333333',
				'woo_form_input_placeholder_color' => '#333333',
				'woo_form_input_border_color' => '#333333',
				'woo_form_input_border_size' => 1,
				'woo_form_input_padding' => 0.6,
				'woo_form_input_border_radius' => 1,
				'woo_form_labels_font_size' => 15,
				'woo_form_title_font_size' => 25,
				'woo_form_labels_font_color' => '#333333',
				'woo_form_title_color' => '#333333',
				'woo_form_select2_height' => 28,
				'woo_form_select2_padding' => 10,
				'woo_product_variations_select_height' => 50,
				'woo_product_variations_reset_margin' => 10,
				'woo_product_variations_label_margin' => 10,
				'woo_product_variations_add_to_cart_btn_margin_top' => 3,
				'woo_product_variations_add_to_cart_btn_margin_left' => 3,
				'woo_product_button_font_color' => '#ffffff',
				'woo_product_button_color' => '#a46497',
				'woo_product_button_color_hover' => '#935386',
				'woo_product_input_background_color' => '#ffffff',
				'woo_product_input_color' => '#333333',
				'woo_product_input_label_color' => '#333333',
				'woo_product_input_padding' => 10,
				'woo_product_input_label_font_size' => 15,
				'woo_product_button_border_radius' => 1,
				'woo_product_input_border_radius' => 1,
				'woo_product_tab_table_border_size' => 1,
				'woo_product_tab_table_border_padding' => 6,
				'woo_product_review_stars_color' => '#333333',
				'woo_product_button_padding' => 10,
				'woo_product_button_margin' => 0,
				'woo_sidebar_slider_background_color' => '#333333',
				'woo_sidebar_slider_range_background_color' => '#333333',
				'woo_sidebar_slider_handler_background_color' => '#333333',
				'woo_sidebar_price_range_color' => '#333333',
				'woo_general_font' => 'Arial, sans-serif',
				'woo_checkout_payment_background_color' => '#eeeeee',
				'woo_checkout_payment_text_color' => '#333333',
				'woo_coupon_code_width' => 100,
				'woo_notification_info_background_color' => '#f7f6f7',
				'woo_notification_info_text_color' => '#515151',
				'woo_notification_info_border_color' => '#1e85be',
				'woo_notification_info_border_size' => 3,
				'woo_notification_error_background_color' => '#f7f6f7',
				'woo_notification_error_text_color' => '#515151',
				'woo_notification_error_border_color' => '#ffc5c2',
				'woo_notification_error_border_size' => 3,
				'woo_notification_message_background_color' => '#f7f6f7',
				'woo_notification_message_text_color' => '#515151',
				'woo_notification_message_border_color' => '#8fae1b',
				'woo_notification_message_border_size' => 3,
			),
	);
}